from fastapi import APIRouter
from app.schemas.question import Question
from app.services.rag_chain import create_rag_chain

router = APIRouter(tags=["Question answering"], prefix="/predict")

GOOGLE_API_KEY = "AIzaSyCZ1fsZwngAfEpo5eUShZEuBctZuuEGEU4"


@router.post("/")
def predict(question: Question):
    """
    Predicts a response based on the given question using a Retrieval-Augmented Generation (RAG) chain.
    Args:
        question (Question): The question object containing the message to be processed.
    Returns:
        dict: A dictionary containing the response generated by the RAG chain.
    """

    columns_to_use = [
        "ingredients",
        "ingredientMeasures",
        "glassType",
        "category",
        "alcoholic",
        "name",
        "text",
    ]

    rag_chain = create_rag_chain(
        csv_path="final_cocktails.csv",
        google_api_key=GOOGLE_API_KEY,
        columns_to_use=columns_to_use,
    )

    return {"response": rag_chain.invoke(question.msg)}
